# Generated by Django 5.0.2 on 2024-02-24 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("littlelemonapi", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("no_of_guests", models.IntegerField()),
                ("bookingdate", models.DateTimeField()),
            ],
        ),
    ]
